# Generated by Django 3.2.9 on 2022-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Название')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('continent', models.CharField(max_length=300, verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Остров',
                'verbose_name_plural': 'Острова',
            },
        ),
    ]
